"""Create calls table with new fields

Revision ID: 8099da81effd
Revises:
Create Date: 2025-08-02 02:07:03.707797

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8099da81effd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("embedding", sa.Text(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("agent_talk_ratio", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(op.f("ix_calls_agent_id"), "calls", ["agent_id"], unique=False)
    op.create_index(op.f("ix_calls_start_time"), "calls", ["start_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calls_start_time"), table_name="calls")
    op.drop_index(op.f("ix_calls_agent_id"), table_name="calls")
    op.drop_table("calls")
    # ### end Alembic commands ###
